### PR TITLE
OOP school library: add Person, Student and Teacher classes

### PR DESCRIPTION
**Pull request by Rhaegar121**
In this PR, I have completed the following tasks.

1. Setup linters
2. Used correct Gitflow
3. Created class Person according to given requirements
4. Created class Student according to given requirements
5. Created class Teacher according to given requirements
6. Updated readme file

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Rhaegar121 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a descriptive [branch name](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects),  All sections from the microverse template should be present in your readme, you are still missing some sections, kindly add them.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by tresorsawasawa — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Rhaegar121 ,:wave: :wave: 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 🛑

You have submitted a project that doesn't have a professional README. Make sure you update your README in order to match the **[required template](https://github.com/microverseinc/readme-template)**.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by rloterh — COMMENTED** [review]
Hi Barry, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly ensure that your ReadMe is professionally documented:
  * Please add the Table of Content section
  * All main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the _FAQ_ section is optional.

- [NOT A REASON FOR INVALIDATION] I also urge you to kindly fix the broken MIT license link in your ReadMe .

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Rhaegar121** [comment]
Hi @rloterh , I have added the Table of content section and all main headers for the readme template. Can you check again and tell me what I actually missing? Also, is this really necessary to mark invalid 4 times because I don't use my readme exactly from the Microverse readme template? In order to create a professional readme, is there only one way to be exact from the template?

**Comment by rloterh** [comment]
Hi @Rhaegar121 
This is the link to your project where the ReadMe is seen: [link](https://github.com/Rhaegar121/OOP-School-Library/tree/feature).
Apparently, the table of contents is not visible in the ReadMe. I urge you to ensure all changes (particularly pertaining to the ReadMe) is committed and pushed the branch under which this activity was submitted for review.

Cheers! 😃

**Review by TedLivist — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Rhaegar121,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You mentioned that you have added the table of contents suggested but that is not so. You do not have the Table of Contents, currently. Kindly add the links in [the template](https://github.com/microverseinc/readme-template) and ensure they are properly linked to appropriate sections in the README - for example the "Install" link on the Table of Contents should lead to the Install section on the README.

Your README (no ToC) | Temple with the table of contents
:---:|:---:
djaa | sisa


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
